language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 4

  - curl http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source

  - chmod a+x vendor/bin/codecept

  - chmod -R 777 App/Tests/_log
  - chmod -R 777 App/Templates/_cache

  - chmod a+x travis_dependencies.sh
  - ./travis_dependencies.sh
script: "vendor/bin/codecept run unit"
